server:
  port: 8082

spring:
  application:
    name: wealth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/wealth_db
    username: bank_user
    password: ${WEALTH_DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

wealth:
  market-price:
    max-age: ${WEALTH_MARKET_PRICE_MAX_AGE:30s}

  outbox:
    publisher:
      fixed-delay: ${WEALTH_OUTBOX_FIXED_DELAY:2000}
      batch-size: ${WEALTH_OUTBOX_BATCH_SIZE:50}
      max-retries: ${WEALTH_OUTBOX_MAX_RETRIES:10}



  cloud:
    stream:
      bindings:
        positionChangedInput-in-0:
          destination: wealth.position.changed
          group: wealth-position-consumer
          content-type: application/json

      kafka:
        bindings:
          positionChangedInput-in-0:
            consumer:
              enableDlq: true
              dlqName: wealth.position.changed.dlq
              autoCommitOffset: false


