package org.fincore.identity.shared.error;

public enum ErrorCode {

    VALIDATION_ERROR,
    DUPLICATE_USERNAME,
    RESOURCE_NOT_FOUND,
    INTERNAL_ERROR,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,
    ACCOUNT_PENDING

}
